name: CI/CD Pipeline

# Déclenche ce workflow sur les pull requests vers la branche main afin qu'elle ne contienne que des commits de merge (de PR)
on:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - main # ajout d'un job pour le déploiement continu sur la branche principale lorsque les changements seront fusionnés

# Définition du job de build pour la pull request
jobs:
  build:
    # Utilisation de la dernière version d'Ubuntu comme environnement d'exécution
    runs-on: ubuntu-latest

    steps:
    # Checkout du code du dépôt
    - uses: actions/checkout@v2

    # Installation de Rust avec rustup
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    # Installation des dépendances du projet (s'il y a des dépendances spécifiques)
    - name: Install dependencies
      run: cargo fetch

    # Exécution du linter pour vérifier le respect des conventions de code
    - name: Run Linter
      run: cargo clippy -- -D warnings

    # Exécution des tests pour s'assurer que le code fonctionne comme prévu
    - name: Run tests
      run: cargo test

    # Construction du projet, préparation pour le déploiement ou la livraison
    - name: Build
      run: cargo build --release
