name: build
on: push
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.2'
          channel: stable
      - name: Build apk
        run: |
          flutter pub get
          # Supprimez ou commentez la ligne suivante si elle pose problème
          # flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build apk --debug
        working-directory: ./client_app

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.2'  # Utilisez la même version de Flutter que pour la build apk
          channel: stable 
      - name: Build web
        run: |
          flutter pub get
          # Supprimez ou commentez la ligne suivante si elle pose problème
          # flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build web
        working-directory: ./client_app
