name: CI_CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Rust setup et build
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Build Rust 
      run: cargo build --verbose
      working-directory: ./secured-api
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./secured-api
    
    # Flutter setup and build
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.4.3'

    - name: Flutter Pub Get
      run: flutter pub get
      working-directory: ./client_app

    - name: Analyze Flutter code
      run: flutter analyze
      working-directory: ./client_app

    - name: Run Flutter tests
      run: flutter test
      working-directory: ./client_app
